#!/usr/bin/env python3.9

#  Copyright (c) 2021. Bohdan Kolvakh
#  This file is part of PyAccounts.
#
#  PyAccounts is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  PyAccounts is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with PyAccounts.  If not, see <https://www.gnu.org/licenses/>.

"""
Extends Gtk stubs generated by PyCharm to include our pythonic properties.
This way, we get autocompletion for them.
See _getattr and _setattr from gtk_utils module for more details.
"""

for module in ("Gtk", "Gdk", "Gio"):
    module = "Gtk"
    _in = open(f"stubs/{module}.pyi")
    out = open(f"stubs/out-{module}.pyi", "w")

    for line in _in.readlines():
        out.write(line)

        if line.startswith("    def get_"):
            line

        for prop in props:
            print(f"    {prop} = ...\n")
            # out.write(f"    {prop} = ...\n")
    break
